### ISSUE TITLE
Picarro concentrations extracted, but...

### ISSUE THREAD

**Issue by kaizadp** [PNNL-TES/TES-drydown#10]
@stephpenn1 
I have extracted the concentrations from the picarro files. (See commit 740ea83626acfbf47e3902456e3593106f85dbec).

Two problems:
1. I am unable to compile the CPCRW concentrations (Issue #9)
2. The SR compiled file alone has 11,000+ observations, so it's going to be a PIA to analyze/plot. 

I believe the current timestep is ~50 seconds (and the instrument ran for an entire year). We'll need to winnow down the number of observations somehow, for ease of operations, but also to make it more consistent with the EGM timepoints.

I'm out of ideas right now, I need some time to think about this.

Also looping in @bpbond and @SarahFansler 

![image](https://user-images.githubusercontent.com/50244730/92181494-5f5fe500-ee17-11ea-8fcd-3210fa1c1547.png)

**Comment by bpbond** [comment]
What's the problem, exactly? 11K observations isn't particularly big.

**Comment by kaizadp** [comment]
RStudio froze when I tried to process this file, and it took me > 5 minutes to plot this one figure. So I’m a little cautious about working with this file directly, making graphs, etc. 

And this is just SR data, from July to December 2019. The CPCRW dataset is even bigger, from Dec 2018 to Dec 2019. At some point, we may have to merge the two files/sites for a combined figure. 

Of course, it could just be my shitty laptop, which freaks out any time I try to process anything > 5 MB 🙄

**Comment by bpbond** [comment]
I'm guessing door (b), shitty laptop, may be the problem here. 😆   But 😕

**Comment by stephpenn1** [comment]
What is the measurement frequency of the EGM measurements @kaizadp ? For consistency I think the picarro should be averaged to a common frequency 

Also what does SR stand for?

**Comment by kaizadp** [comment]
The EGM readings were taken once a day over ~3 weeks.

SR is Secret River (the site in WA)

**Comment by stephpenn1** [comment]
FYI I just tried plotting the picarro data - my RStudio crashed when i tried to plot, but once i changed the `DATETIME` variable to a date instead a character it plotted very quickly

**Comment by kaizadp** [comment]
Yay!

**Comment by stephpenn1** [comment]
@kaizadp is the raw picarro in ppb or ppm?

**Comment by kaizadp** [comment]
Ppm

**Comment by stephpenn1** [comment]
I'm gonna close this issue and mark it as `"Kaizad needs a new computer"`

i'll open a new issue when i have plots to share
