### ISSUE TITLE
using headspace in flux measurements? 

### ISSUE THREAD

**Issue by kaizadp** [PNNL-TES/TES-drydown#14]
Does the Picarro script not use headspace for flux calculations? Maybe I missed it somewhere, but I don't see it.
@bpbond 

https://github.com/PNNL-TES/TES-drydown/blob/8b504af23d65312c715ddf23990e9338835a9a10/code/2-picarro_data.R#L94-L97

**Comment by bpbond** [comment]
The package code asks for `volume_cm3` which is total volume CO2 is circulating in: the Picarro laser cavity, tubing, and any sample headspace. The code snippet above is ignoring headspace, yes (or implicitly including it in the tubing I guess).

**Comment by kaizadp** [comment]
great, thanks
