### ISSUE TITLE
Picarro script

### ISSUE THREAD

**Issue by kaizadp** [PNNL-TES/TES-drydown#5]
https://github.com/PNNL-TES/TES-drydown/blob/6a7f0cea93e6bc343a68dc8548461d8369bb9321/3c-picarro_output.R#L43

The drake plan didn't work, so I'm going line by line. Got an error at `match_picarro_data`.

> Error in pd_match_count[matches] <- pd_match_count[matches] + 1 : 
>   NAs are not allowed in subscripted assignments

@bpbond

**Comment by bpbond** [comment]
Is this fixed? Should I dive in and look?

**Comment by kaizadp** [comment]
Not fixed. Yes, please dive in. Thanks

**Comment by bpbond** [comment]
Completely confused. So you're working on your branch, and getting an error in `3c-picarro_output.R`? I can't even get the `1-initial_processing.R` script to run...does it work for you?

**Comment by kaizadp** [comment]
That's weird. I just ran `1-initial_processing.R` fine.

But -- outputs from script-1 are in the `data/processed` directory. You can use those directly for script-3c. And yes, I'm getting an error in `3c-picarro_output.R`.

**Comment by kaizadp** [comment]
Where's your error in `1-initial_processing.R`?

**Comment by kaizadp** [comment]
fixed
