### ISSUE TITLE
importing data from Google Drive

### ISSUE THREAD

**Issue by kaizadp** [PNNL-TES/TES-drydown#6]
@bpbond 

The code currently imports Picarro data from the local working directory. Can't do that for the full dataset, it's too big. Need your help to import this from [Google Drive](https://drive.google.com/drive/folders/1RVANlM-t_9OrHY-PSxk4Zgi0-j5h4r5_?usp=sharing).

https://github.com/PNNL-TES/TES-drydown/blob/a4e48fc882a0c6b0745bb12ba3a85abbb692c353/3c-picarro_output.R#L35-L36

**Comment by bpbond** [comment]
😕  The Picarro files are too large? It looks like they're 'only' a couple hundred megabytes...are you getting an error? I'm confused.

**Comment by kaizadp** [comment]
I haven't run it in R yet. I've been too scared to download the files from GDrive to my computer, because my system and OneDrive freaked out the last time I did that (for 3soils, I think). 

Ooh, I guess I could download and compress. That way I'm working with only one file that's smaller than the entire dataset.
So nvm on the GDrive question then. But we should have a separate conversation later about downloading data to the local directory vs. pulling directly from GDrive into R.
